spring.application.name=urlshortener

# -----------------------
# Without Docker Service
# -----------------------
# spring.datasource.url=jdbc:mysql://localhost:3306/url_shortener

# -----------------------
# Docker Service
# -----------------------
spring.datasource.url=jdbc:mysql://mysql:3306/url_shortener
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

# ----------------------
# REDIS without docker
# ----------------------
# spring.data.redis.host=localhost
# spring.data.redis.port=6379

# -----------------------
# REDIS (Docker Service)
# -----------------------
spring.data.redis.host=redis
spring.data.redis.port=6379